[user]
name = 'Tobias Becker'
email = 'tobiasbecker@microsoft.com'

[ui]
default-command = 'log'
merge-editor = 'vscode'
# The only two special values for this are "meld-3" and "diffedit3".
# Otherwise this needs an executable, possibly with path.
#diff-editor = 'code'
# Best to keep unset for the handy TUI.

[remotes.origin]
auto-track-bookmarks = 'glob-i:"user/tobiasbecker/*" | glob-i:"user/cmdq/*"'

[git]
push-bookmark-prefix = 'user/cmdq/push-'
private-commits = "description('wip:*') | description('private:*')"

[aliases]
bntip = ['util', 'exec', '--', 'bash', '-c', 'jj edit "bookmark_nonempty_tip(\"$1\")"', '']
btip = ['util', 'exec', '--', 'bash', '-c', 'jj edit "bookmark_tip(\"$1\")"', '']
ntip = ['edit', 'stack_nonempty_tip(@)']
slide = ['util', 'exec', '--', 'bash', '-c', 'jj bookmark move "$1" --to "bookmark_nonempty_tip(\"$1\")"', '']
tip = ['edit', 'stack_tip(@)']

[revset-aliases]
'bookmark_nonempty_tip(b)' = 'latest(b:: ~ empty())'
'bookmark_tip(b)' = 'latest(b::)'
'immutable_heads()' = 'builtin_immutable_heads() | remote_bookmarks()'
'stack_nonempty_tip(x)' = 'latest(x:: ~ empty())'
'stack_tip(x)' = 'latest(x::)'
push_target = 'latest(::@ ~ empty())'

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
